# Railway Production Deployment Configuration
[build]
  builder = "nixpacks"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  startCommand = "npm run backend"

[env]
  NODE_ENV = "production"
  # IONET_API_KEY will be set via Railway environment variables
  # TAOSTATS_API_USERNAME will be set via Railway environment variables  
  # TELEGRAM_BOT_TOKEN will be set via Railway environment variables
  # CLAUDE_API_KEY will be set via Railway environment variables